### ISSUE TITLE
Page sometimes gets redirected to Invidious page hosting video contained in original page

### ISSUE THREAD

**Issue by edgar-vincent** [kssytsrk/nx-freestance-handler#13] opened 2021-07-10 09:41 UTC
Hi!

Thanks a lot for your very useful package. I have been encountering a strange issue with it: when I open some websites, the current buffer gets redirected to the Invidious page on which a video contained in the original page I opened is hosted.

For example, with the latest version of `nx-freestance-handler`, `freestance.lisp` containing:

```
(push #'nx-freestance-handler:invidious-handler *my-request-resource-handlers*)
(push #'nx-freestance-handler:teddit-handler *my-request-resource-handlers*)

(setf nx-freestance-handler:*preferred-nitter-instance* "nitter.fdn.fr")
```
and `init.lisp` containing only:

```
(defvar *my-request-resource-handlers* '())
(load-after-system :nx-freestance-handler (nyxt-init-file "freestance.lisp"))

(define-configuration web-buffer
  ((request-resource-hook
    (reduce #'hooks:add-hook
            (mapcar #'make-handler-resource
		    *my-request-resource-handlers*)
            :initial-value %slot-default%))))
```

opening https://www.huntbikewheels.com/ redirects me to https://invidious-us.kavin.rocks/embed/qEn2Uc9WQM4?rel=0&showinfo=0&vq=720

Thanks again!

EV

**Comment by kssytsrk** [comment] 2021-07-10 11:03
Hello, thanks for using the package and reporting this. I've noticed it some time ago too, but sadly this seems to be a Nyxt (or even WebKit?) problem, take a look at [this](/atlas-engineer/nyxt/issues/980) issue. But it's possible Nyxt's devs made some progress since then and disabling embedded videos' redirection is now attainable, you (or I - however you prefer) can ping them in the issue asking for any updates on the matter :)

**Comment by edgar-vincent** [comment] 2021-07-10 11:44
I've pinged the dev team. They're used to me being annoying :) Thanks for your quick reply.

**Comment by aartaka** [comment] 2021-12-02 20:09
Sorry for the delay. It should be fixed on the Nyxt side now (see Nyxt commit b3a2cbd4929731ae652dac47f5b4b1cdce254a50).

**Comment by edgar-vincent** [comment] 2021-12-02 20:42
Seems to work properly so far. Thank you very much @aartaka!

Edit: I spoke too hastily. When I open https://kitchingroup.cheme.cmu.edu/blog/2014/05/12/Autogenerating-functions-in-emacs-lisp/, for instance, I don't get redirected to Nitter, as I used to, but I get the following errors:

```
<INFO> [21:51:50] Loading "https://kitchingroup.cheme.cmu.edu/blog/2014/05/12/Autogenerating-functions-in-emacs-lisp/".
<INFO> [21:51:52] Switching to Nitter: "https://nitter.net/widgets/widget_iframe.a53eecb4584348a2ad32ec2ae21f6eae.html?origin=https%3A%2F%2Fkitchingroup.cheme.cmu.edu"
<WARN> [21:51:52] Warning: Cannot redirect to https://nitter.net/widgets/widget_iframe.a53eecb4584348a2ad32ec2ae21f6eae.html?origin=https%3A%2F%2Fkitchingroup.cheme.cmu.edu in an iframe, forwarding to the original URL (https://platform.twitter.com/widgets/widget_iframe.a53eecb4584348a2ad32ec2ae21f6eae.html?origin=https%3A%2F%2Fkitchingroup.cheme.cmu.edu).
<INFO> [21:51:52] Switching to Nitter: "https://nitter.net/widgets/widget_iframe.a53eecb4584348a2ad32ec2ae21f6eae.html?origin=https%3A%2F%2Fkitchingroup.cheme.cmu.edu"
<WARN> [21:51:52] Warning: Cannot redirect to https://nitter.net/widgets/widget_iframe.a53eecb4584348a2ad32ec2ae21f6eae.html?origin=https%3A%2F%2Fkitchingroup.cheme.cmu.edu in an iframe, forwarding to the original URL (https://platform.twitter.com/widgets/widget_iframe.a53eecb4584348a2ad32ec2ae21f6eae.html?origin=https%3A%2F%2Fkitchingroup.cheme.cmu.edu).
<INFO> [21:51:53] Finished loading "https://kitchingroup.cheme.cmu.edu/blog/2014/05/12/Autogenerating-functions-in-emacs-lisp/".
<INFO> [21:51:54] Switching to Nitter: "https://nitter.net/widgets/tweet_button.a53eecb4584348a2ad32ec2ae21f6eae.en.html#dnt=false&id=twitter-widget-1&lang=en&original_referer=https%3A%2F%2Fkitchingroup.cheme.cmu.edu%2Fblog%2F2014%2F05%2F12%2FAutogenerating-functions-in-emacs-lisp%2F&size=m&text=Autogenerating%20functions%20in%20emacs-lisp&time=1638478314191&type=share&url=https%3A%2F%2Fkitchingroup.cheme.cmu.edu%2Fblog%2F2014%2F05%2F12%2FAutogenerating-functions-in-emacs-lisp%2F&via=johnkitchin"
<WARN> [21:51:54] Warning: Cannot redirect to https://nitter.net/widgets/tweet_button.a53eecb4584348a2ad32ec2ae21f6eae.en.html#dnt=false&id=twitter-widget-1&lang=en&original_referer=https%3A%2F%2Fkitchingroup.cheme.cmu.edu%2Fblog%2F2014%2F05%2F12%2FAutogenerating-functions-in-emacs-lisp%2F&size=m&text=Autogenerating%20functions%20in%20emacs-lisp&time=1638478314191&type=share&url=https%3A%2F%2Fkitchingroup.cheme.cmu.edu%2Fblog%2F2014%2F05%2F12%2FAutogenerating-functions-in-emacs-lisp%2F&via=johnkitchin in an iframe, forwarding to the original URL (https://platform.twitter.com/widgets/tweet_button.a53eecb4584348a2ad32ec2ae21f6eae.en.html#dnt=false&id=twitter-widget-1&lang=en&original_referer=https%3A%2F%2Fkitchin
group.cheme.cmu.edu%2Fblog%2F2014%2F05%2F12%2FAutogenerating-functions-in-emacs-lisp%2F&size=m&text=Autogenerating%20functions%20in%20emacs-lisp&time=1638478314191&type=share&url=https%3A%2F%2Fkitchingroup.cheme.cmu.edu%2Fblog%2F2014%2F05%2F12%2FAutogenerating-functions-in-emacs-lisp%2F&via=johnkitchin).
<INFO> [21:51:55] Switching to Nitter: "https://nitter.net/widgets/tweet_button.a53eecb4584348a2ad32ec2ae21f6eae.en.html#dnt=false&id=twitter-widget-1&lang=en&original_referer=https%3A%2F%2Fkitchingroup.cheme.cmu.edu%2Fblog%2F2014%2F05%2F12%2FAutogenerating-functions-in-emacs-lisp%2F&size=m&text=Autogenerating%20functions%20in%20emacs-lisp&time=1638478314191&type=share&url=https%3A%2F%2Fkitchingroup.cheme.cmu.edu%2Fblog%2F2014%2F05%2F12%2FAutogenerating-functions-in-emacs-lisp%2F&via=johnkitchin"
<WARN> [21:51:55] Warning: Cannot redirect to https://nitter.net/widgets/tweet_button.a53eecb4584348a2ad32ec2ae21f6eae.en.html#dnt=false&id=twitter-widget-1&lang=en&original_referer=https%3A%2F%2Fkitchingroup.cheme.cmu.edu%2Fblog%2F2014%2F05%2F12%2FAutogenerating-functions-in-emacs-lisp%2F&size=m&text=Autogenerating%20functions%20in%20emacs-lisp&time=1638478314191&type=share&url=https%3A%2F%2Fkitchingroup.cheme.cmu.edu%2Fblog%2F2014%2F05%2F12%2FAutogenerating-functions-in-emacs-lisp%2F&via=johnkitchin in an iframe, forwarding to the original URL (https://platform.twitter.com/widgets/tweet_button.a53eecb4584348a2ad32ec2ae21f6eae.en.html#dnt=false&id=twitter-widget-1&lang=en&original_referer=https%3A%2F%2Fkitchingroup.cheme.cmu.edu%2Fblog%2F2014%2F05%2F12%2FAutogenerating-functions-in-emacs-lisp%2F&size=m&text=Autogenerating%20functions%20in%20emacs-lisp&time=1638478314191&type=share&url=https%3A%2F%2Fkitchingroup.cheme.cmu.edu%2Fblog%2F2014%2F05%2F12%2FAutogenerating-functions-in-emacs-lisp%2F&via=johnkitchin).
<INFO> [21:51:55] Switching to Nitter: "https://nitter.net/i/jot"
<WARN> [21:51:55] Warning: Cannot redirect to https://nitter.net/i/jot in an iframe, forwarding to the original URL (https://syndication.twitter.com/i/jot).
<INFO> [21:51:55] Switching to Nitter: "https://nitter.net/jot.html"
<WARN> [21:51:55] Warning: Cannot redirect to https://nitter.net/jot.html in an iframe, forwarding to the original URL (https://platform.twitter.com/jot.html).
<INFO> [21:51:56] Switching to Nitter: "https://nitter.net/jot.html"
<WARN> [21:51:56] Warning: Cannot redirect to https://nitter.net/jot.html in an iframe, forwarding to the original URL (https://platform.twitter.com/jot.html).
```

Is this issue related to the problem at hand or is it a different one?

Thanks again.

**Comment by aartaka** [comment] 2021-12-02 20:59
> Seems to work properly so far. Thank you very much @aartaka!
> 
> Edit: I spoke too hastily. When I open https://kitchingroup.cheme.cmu.edu/blog/2014/05/12/Autogenerating-functions-in-emacs-lisp/, for instance, I don't get redirected to Nitter, as I used to, but I get the following errors:
> 
> ```
> <INFO> [21:51:50] Loading "https://kitchingroup.cheme.cmu.edu/blog/2014/05/12/Autogenerating-functions-in-emacs-lisp/".
> <INFO> [21:51:52] Switching to Nitter: "https://nitter.net/widgets/widget_iframe.a53eecb4584348a2ad32ec2ae21f6eae.html?origin=https%3A%2F%2Fkitchingroup.cheme.cmu.edu"
> <WARN> [21:51:52] Warning: Cannot redirect to https://nitter.net/widgets/widget_iframe.a53eecb4584348a2ad32ec2ae21f6eae.html?origin=https%3A%2F%2Fkitchingroup.cheme.cmu.edu in an iframe, forwarding to the original URL (https://platform.twitter.com/widgets/widget_iframe.a53eecb4584348a2ad32ec2ae21f6eae.html?origin=https%3A%2F%2Fkitchingroup.cheme.cmu.edu).
> <INFO> [21:51:52] Switching to Nitter: "https://nitter.net/widgets/widget_iframe.a53eecb4584348a2ad32ec2ae21f6eae.html?origin=https%3A%2F%2Fkitchingroup.cheme.cmu.edu"
> <WARN> [21:51:52] Warning: Cannot redirect to https://nitter.net/widgets/widget_iframe.a53eecb4584348a2ad32ec2ae21f6eae.html?origin=https%3A%2F%2Fkitchingroup.cheme.cmu.edu in an iframe, forwarding to the original URL (https://platform.twitter.com/widgets/widget_iframe.a53eecb4584348a2ad32ec2ae21f6eae.html?origin=https%3A%2F%2Fkitchingroup.cheme.cmu.edu).
> <INFO> [21:51:53] Finished loading "https://kitchingroup.cheme.cmu.edu/blog/2014/05/12/Autogenerating-functions-in-emacs-lisp/".
> <INFO> [21:51:54] Switching to Nitter: "https://nitter.net/widgets/tweet_button.a53eecb4584348a2ad32ec2ae21f6eae.en.html#dnt=false&id=twitter-widget-1&lang=en&original_referer=https%3A%2F%2Fkitchingroup.cheme.cmu.edu%2Fblog%2F2014%2F05%2F12%2FAutogenerating-functions-in-emacs-lisp%2F&size=m&text=Autogenerating%20functions%20in%20emacs-lisp&time=1638478314191&type=share&url=https%3A%2F%2Fkitchingroup.cheme.cmu.edu%2Fblog%2F2014%2F05%2F12%2FAutogenerating-functions-in-emacs-lisp%2F&via=johnkitchin"
> <WARN> [21:51:54] Warning: Cannot redirect to https://nitter.net/widgets/tweet_button.a53eecb4584348a2ad32ec2ae21f6eae.en.html#dnt=false&id=twitter-widget-1&lang=en&original_referer=https%3A%2F%2Fkitchingroup.cheme.cmu.edu%2Fblog%2F2014%2F05%2F12%2FAutogenerating-functions-in-emacs-lisp%2F&size=m&text=Autogenerating%20functions%20in%20emacs-lisp&time=1638478314191&type=share&url=https%3A%2F%2Fkitchingroup.cheme.cmu.edu%2Fblog%2F2014%2F05%2F12%2FAutogenerating-functions-in-emacs-lisp%2F&via=johnkitchin in an iframe, forwarding to the original URL (https://platform.twitter.com/widgets/tweet_button.a53eecb4584348a2ad32ec2ae21f6eae.en.html#dnt=false&id=twitter-widget-1&lang=en&original_referer=https%3A%2F%2Fkitchin
> group.cheme.cmu.edu%2Fblog%2F2014%2F05%2F12%2FAutogenerating-functions-in-emacs-lisp%2F&size=m&text=Autogenerating%20functions%20in%20emacs-lisp&time=1638478314191&type=share&url=https%3A%2F%2Fkitchingroup.cheme.cmu.edu%2Fblog%2F2014%2F05%2F12%2FAutogenerating-functions-in-emacs-lisp%2F&via=johnkitchin).
> <INFO> [21:51:55] Switching to Nitter: "https://nitter.net/widgets/tweet_button.a53eecb4584348a2ad32ec2ae21f6eae.en.html#dnt=false&id=twitter-widget-1&lang=en&original_referer=https%3A%2F%2Fkitchingroup.cheme.cmu.edu%2Fblog%2F2014%2F05%2F12%2FAutogenerating-functions-in-emacs-lisp%2F&size=m&text=Autogenerating%20functions%20in%20emacs-lisp&time=1638478314191&type=share&url=https%3A%2F%2Fkitchingroup.cheme.cmu.edu%2Fblog%2F2014%2F05%2F12%2FAutogenerating-functions-in-emacs-lisp%2F&via=johnkitchin"
> <WARN> [21:51:55] Warning: Cannot redirect to https://nitter.net/widgets/tweet_button.a53eecb4584348a2ad32ec2ae21f6eae.en.html#dnt=false&id=twitter-widget-1&lang=en&original_referer=https%3A%2F%2Fkitchingroup.cheme.cmu.edu%2Fblog%2F2014%2F05%2F12%2FAutogenerating-functions-in-emacs-lisp%2F&size=m&text=Autogenerating%20functions%20in%20emacs-lisp&time=1638478314191&type=share&url=https%3A%2F%2Fkitchingroup.cheme.cmu.edu%2Fblog%2F2014%2F05%2F12%2FAutogenerating-functions-in-emacs-lisp%2F&via=johnkitchin in an iframe, forwarding to the original URL (https://platform.twitter.com/widgets/tweet_button.a53eecb4584348a2ad32ec2ae21f6eae.en.html#dnt=false&id=twitter-widget-1&lang=en&original_referer=https%3A%2F%2Fkitchingroup.cheme.cmu.edu%2Fblog%2F2014%2F05%2F12%2FAutogenerating-functions-in-emacs-lisp%2F&size=m&text=Autogenerating%20functions%20in%20emacs-lisp&time=1638478314191&type=share&url=https%3A%2F%2Fkitchingroup.cheme.cmu.edu%2Fblog%2F2014%2F05%2F12%2FAutogenerating-functions-in-emacs-lisp%2F&via=johnkitchin).
> <INFO> [21:51:55] Switching to Nitter: "https://nitter.net/i/jot"
> <WARN> [21:51:55] Warning: Cannot redirect to https://nitter.net/i/jot in an iframe, forwarding to the original URL (https://syndication.twitter.com/i/jot).
> <INFO> [21:51:55] Switching to Nitter: "https://nitter.net/jot.html"
> <WARN> [21:51:55] Warning: Cannot redirect to https://nitter.net/jot.html in an iframe, forwarding to the original URL (https://platform.twitter.com/jot.html).
> <INFO> [21:51:56] Switching to Nitter: "https://nitter.net/jot.html"
> <WARN> [21:51:56] Warning: Cannot redirect to https://nitter.net/jot.html in an iframe, forwarding to the original URL (https://platform.twitter.com/jot.html).
> ```
> 
> Is this issue related to the problem at hand or is it a different one?

This is an intended behavior to make it clear we cannot redirect iframes :)

**Comment by edgar-vincent** [comment] 2021-12-02 21:01
Oh brilliant. Sorry about that. Thanks @aartaka. You're doing wonders, as usual.

**Comment by aartaka** [comment] 2021-12-02 21:30
> Oh brilliant. Sorry about that. Thanks @aartaka. You're doing wonders, as usual.

No problem, glad to help :)

**Comment by kiranandcode** [comment] 2021-12-06 03:37
Just ran into this issue myself as well, great to hear that it's been fixed. Thanks for the great work.

**Closed as completed** 2021-12-17 13:27 UTC
